config/routes.rb
Rails.application.routes.draw do

  root 'home#router'
  resources :users, only: [:edit, :update, :destroy] do
    get :initiate_new_demo, on: :collection
  end
  resources :payments, only: [:index, :show, :create]
  resources :subscriptions, only: [:new, :create, :destroy]
  resources :plans, only: [:new, :index]
  match '/auth/:provider/callback', to: 'auth#create', via: [:get, :post]
  get '/logout', to: 'auth#destroy'
  get '/dashboard', to: 'home#dashboard'
  post '/stripe/webhook', to: 'subscriptions#webhook'
  get '/:handle' => 'payments#new', as: :new_payment
end

app/views/shared/_demo_notice.html.erb
<div id="demo-notice">
  This is a temporary demo account. To finish your registration, <a href="/auth/stripe_connect?scope=read_write">click here</a>.
</div>

app/views/shared/_header.html.erb
<header id="main-header" class="non-transparent-header">
<nav id="main-navigation" class="non-transparent-nav of<%= ' demo-notice' if current_user.demo == true %>">
    <div class="inner">
      <div class="logo alpha">
        <a href="/" class="txt">Payzo.io</a>
    </div>

      <% if current_user.demo != true %>
        <div class="account-status alpha">
          <p>
            <% if current_user.current_subscription.remaining_limit == false %>
              <strong>Pro (unlimited) plan</strong> <a href="/subscriptions/new" class="blue-link">Change</a>
            <% else %>
              <strong>$<%= current_user.current_subscription.transactions_last_32_days.to_i %> used</strong> / $<%= current_user.current_subscription.current_plan_limit %> limit (last 32 days) <a href="/subscriptions/new" class="blue-link">View plans</a>
            <% end %>
          </p>
        </div>
      <% end %>

      <div class="menu-items omega">
          <a href="/logout">Logout</a>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_sidebar_navigation.html.erb
<nav id="sidebar-navigation">
  <ul>

    <li><%= link_to "Dashboard", {:controller => "home", :action => "dashboard"},
      :class => current_page?(controller: "home", action: "dashboard") ? "active" : "" %></li>

    <li><%= link_to "Payments", payments_path, 
      :class => controller.controller_name == 'payments' ? "active" : "" %></li>

    <li><%= link_to "Plans", plans_path, 
      :class => controller.controller_name == 'plans' ? "active" : "" %></li>

    <% # TODO: add link_tos below once route created %>
    <li><%= link_to "Subscribers", "#" %></li> 
    <li><%= link_to "Settings", "#" %></li>

  </ul>
</nav>