config/routes.rb
Rails.application.routes.draw do

  root 'home#router'
  resources :users, only: [:edit, :update, :destroy] do
    get :initiate_new_demo, on: :collection
  end
  resources :payments, only: [:index, :show, :create]
  resources :subscriptions, only: [:new, :create, :destroy]
  resources :plans, only: [:new, :index]
  match '/auth/:provider/callback', to: 'auth#create', via: [:get, :post]
  get '/logout', to: 'auth#destroy'
  get '/dashboard', to: 'home#dashboard'
  post '/stripe/webhook', to: 'subscriptions#webhook'
  get '/:handle' => 'payments#new', as: :new_payment
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base

  # 0 - free (limit: 200)
  # 1 - $9 (limit: 2000)
  # 2 - $15 (unlimited)
  PLANS = [0, 1, 2]

  belongs_to :user
  has_many :subscription_payments

  validates :plan, inclusion: { in: PLANS }, presence: true
  validates :user, presence: true

  # how much transactions volume is left
  # returns false if unlimited
  def remaining_limit
    return false unless current_plan_limit
    limit = (current_plan_limit - transactions_last_32_days).round
    limit < 0 ? 0 : limit
  end

  def transactions_last_32_days
    user.payments.last_32_days.successful.sum(:amount)
  end

  def current_plan_limit
    return 200   if plan === 0
    return 2000  if plan === 1
    return false if plan === 2
  end

  def paid?
    if plan === 0
      true
    else
      subscription_payments.where("created_at >= ?", 32.days.ago).present?
    end
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

  before_filter :require_login, only: [:new, :create, :destroy]
  protect_from_forgery :except => :webhook

  def new
    if current_user.current_subscription.plan == 0
      @label_free = 'Currently'
      @label_starter = 'Upgrade'
      @label_pro = 'Upgrade'
    elsif current_user.current_subscription.plan == 1
      @label_free = 'Downgrade'
      @label_starter = 'Currently'
      @label_pro = 'Upgrade'
    elsif current_user.current_subscription.plan == 2
      @label_free = 'Downgrade'
      @label_starter = 'Downgrade'
      @label_pro = 'Currently'
    end

    @have_customer_details = current_user.stripe_customer_id.present?
  end

  # TODO: display stripe card form only for the first time subscription is entered
  # for updating, canceling, downgrading or repeated upgrading, don't display it
  def create
    # ensure Stripe customer id (and their card details) is saved
    stripe_customer = nil
    card_error = false

    if current_user.stripe_customer_id.nil?
      if params[:stripeToken]
        begin
          stripe_customer = Stripe::Customer.create(
            :card => params[:stripeToken],
            :email => current_user.email
          )
          current_user.update_attribute(:stripe_customer_id, stripe_customer.id)
        rescue => e
          console.log(e)
          logger.debug(e)
          flash[:alert] = "Your card could not be authorised. Plese check your card limits and try again."
          card_error = true
        end
      else
        console.log("stripeToken not provided")
        logger.debug("stripeToken not provided")
        flash[:alert] = "Your card could not be authorised. Plese check your card limits and try again."
        card_error = true
      end
    else
      stripe_customer = Stripe::Customer.retrieve(current_user.stripe_customer_id)
    end

    head 402 and return if card_error

    # create or update their subscriptions plan
    plan = Plan::OPTIONS.select { |opt| opt[:id].to_s === params[:plan_id].to_s }.first

    if plan.present?
      stripe_subscription = nil

      # customer already has stripe_id = update
      if current_user.current_subscription.stripe_id
        stripe_subscription = stripe_customer.subscriptions.retrieve(current_user.current_subscription.stripe_id)
        stripe_subscription.plan = plan[:name].downcase
        stripe_subscription.save

      # customer doesn't have stripe_id = new subscription, not update
      else
        stripe_subscription = stripe_customer.subscriptions.create(plan: plan[:name].downcase)
      end

      Subscription.create!(plan: plan[:id], user: current_user, stripe_id: stripe_subscription.id).subscription_payments.create!
      redirect_to :back
    else
      raise "Invalid plan id"
    end
  end

  # Downgrade to a free plan
  def destroy
    # cancel monthly stripe subscription
    stripe_customer = Stripe::Customer.retrieve(current_user.stripe_customer_id)
    stripe_customer.subscriptions.retrieve(current_user.current_subscription.stripe_id).delete

    # update subscription records in our database
    current_user.subscriptions.create!(plan: 0)

    redirect_to :back
  end

  # Called by Stripe when new monthly charge happens
  def webhook
    # create a new subscription payment
    # current_user.current_subscription.subscription_payments.create!
    console.log params
    puts params
    render json: params
  end
end

app/views/subscriptions/new.html.erb
<script>
  $(function() {
    Stripe.setPublishableKey('<%= ENV['STRIPE_PUB_KEY'] %>');

    var starter_handler = StripeCheckout.configure({
      key: '<%= ENV['STRIPE_PUB_KEY'] %>',
      token: function(token) {
        $('#upgrade-lutenant-pay').text("Processing...");
        $.post('/subscriptions', { "plan_id": 1, "stripeToken": token.id })
          .complete(function(){
            window.location = '/subscriptions/new';
          });
      }
    });

    // Close Checkout on page navigation
    $(window).on('popstate', function() {
      starter_handler.close();
    });

    var pro_handler = StripeCheckout.configure({
      key: '<%= ENV['STRIPE_PUB_KEY'] %>',
      token: function(token) {
        $('#upgrade-general-pay').text("Processing...");
        $.post('/subscriptions', { "plan_id": 2, "stripeToken": token.id })
          .complete(function(){
            window.location = '/subscriptions/new';
          });
      }
    });

    // Close Checkout on page navigation
    $(window).on('popstate', function() {
      pro_handler.close();
    });

    <% unless @have_customer_details %>
      $('#upgrade-lutenant-pay').on('click', function(e) {
        starter_handler.open({
          name: 'Starter ($9 / month)',
          description: '$2000 / month in transactions limit',
          amount: 900,
          email: "<%= current_user.email %>"
        });
        e.preventDefault();
      });

      $('#upgrade-general-pay').on('click', function(e) {
        pro_handler.open({
          name: 'Pro ($15 / month)',
          description: 'unlimited transactions',
          amount: 1500,
          email: "<%= current_user.email %>"
        });
        e.preventDefault();
      });
    <% end %>
  })
</script>

<header id="main-header" class="non-transparent-header">
  <nav id="main-navigation" class="non-transparent-nav of">
    <div class="inner">
      <div class="logo alpha">
        <a href="/" class="txt">Payzo.io</a>
      </div>
      <div class="menu-items omega">
        <% if current_user %>
          <a href="/logout">Logout</a>
        <% else %>
          <a href="/auth/stripe_connect">Login</a>
        <% end %>
      </div>
    </div>
  </nav>
</header>

<section id="pricing" class="section-row of">
  <div class="inner of">
    <!--<div>
      <a href="#">Monthly</a> / <a href="#">Annual (10% off)</a>
    </div>-->
    <div class="pricing-blocks">
      <% if flash[:alert] %>
        <p><%= flash[:alert] %></p><br>
      <% end %>
      <div class="pricing-scout grid-3 center-txt<%= ' current' if current_user.current_subscription.plan == 0 %>">
        <div class="details">
          <h3>Scout</h3>
          <p>Accept up to $200 / month</p>
          <p><strong>Free</strong></p>
        </div>
        <div class="cta">
          <% if current_user.current_subscription.plan != 0 %>
            <%= link_to @label_free, subscription_url(id: 0), method: :delete, class: 'cta-btn confirm' %>
          <% else %>
            <%= link_to @label_free, '#', class: 'cta-btn' %>
          <% end %>
        </div>
      </div>
      <div class="pricing-lutenant grid-3 center-txt<%= ' current' if current_user.current_subscription.plan == 1 %>">
        <div class="details">
          <h3>Starter</h3>
          <p>Accept up to $2000 / month</p>
          <p><strong>$9 / month</strong></p>
        </div>
        <div class="cta">
          <% if @have_customer_details %>
            <% if current_user.current_subscription.plan != 1 %>
              <%= link_to @label_starter, subscriptions_url(plan_id: 1), method: 'post', class: 'cta-btn confirm', id: 'upgrade-lutenant-pay' %>
            <% else %>
              <%= link_to @label_starter, '#', class: 'cta-btn' %>
            <% end %>
          <% else %>
            <a href="#" class="cta-btn" id="upgrade-lutenant-pay"><%= @label_starter %></a>
          <% end %>
        </div>
      </div>
      <div class="pricing-general grid-3 center-txt<%= ' current' if current_user.current_subscription.plan == 2 %>">
        <div class="details">
          <h3>Pro</h3>
          <p>Unlimited transactions</p>
          <p><strong>$15 / month</strong></p>
        </div>
        <div class="cta">
          <% if @have_customer_details %>
            <% if current_user.current_subscription.plan != 2 %>
              <%= link_to @label_pro, subscriptions_url(plan_id: 2), method: 'post', class: 'cta-btn confirm', id: 'upgrade-general-pay' %>
            <% else %>
              <%= link_to @label_pro, '#', class: 'cta-btn' %>
            <% end %>
          <% else %>
            <a href="#" class="cta-btn" id="upgrade-general-pay"><%= @label_pro %></a>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>