config/routes.rb
Rails.application.routes.draw do

  root 'home#router'
  resources :users, only: [:edit, :update, :destroy] do
    get :initiate_new_demo, on: :collection
  end
  resources :payments, only: [:index, :show, :create]
  resources :subscriptions, only: [:new, :create, :destroy]
  resources :plans, only: [:new, :index]
  match '/auth/:provider/callback', to: 'auth#create', via: [:get, :post]
  get '/logout', to: 'auth#destroy'
  get '/dashboard', to: 'home#dashboard'
  post '/stripe/webhook', to: 'subscriptions#webhook'
  get '/:handle' => 'payments#new', as: :new_payment
end

app/models/plan.rb
class Plan
  OPTIONS = [
              { id: 0, name: 'Scout', price: 0 },
              { id: 1, name: 'Starter', price: 9 },
              { id: 2, name: 'Pro', price: 15 }
            ]
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  layout "sidebar"
  before_filter :require_login

  def index
    #@plans = current_user.plans.all
    @plans = [{},{},{},{},{}]
    #@plans = []
  end

  def new
    #
  end
end

app/views/plans/_plan.html.erb
<% # partial for @plans index %>
<li class="parent">
  <% # plan.name %>
  <span class="plan-name grid-4">Support Retainer</span>
  
  <% # plan.amount %>
  <span class="plan-amount grid-4 center-txt"
    ><%= number_to_currency(2000) %> / month</span>

  <% # plan.subscribers.count %>
  <span class="plan-subscribers grid-4 right-txt"
    >6 Subscribers</span>

  <% # url_for(plan) %>
  <span class="grid-12"><a href="#">payzo.io/your-payment-handle/support-retainer</a></span>
 </li>

app/views/plans/index.html.erb
<% content_for :subheader do %>
<div class="grid-9 prefix-3">
  <%= link_to "New Plan", new_plan_path %>
</div>
<% end %>

<% if @plans.length == 0 then %>
  <p class="empty-collection">Here you can create plans for automated payments
  for your customers.</p>
<% else %>
  <ul class="index plan-index">
    <%= render :partial => "plan", :collection => @plans, :as => :plan %>
  </ul>
<% end %>

</ul>

app/views/plans/new.html.erb
new